mysite/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.UpdatePostView.as_view(), name='post_edit'),
    path('post/<int:pk>/remove', views.DeletePostView.as_view(), name='post_remove'),
    path('post/save_as_draft', views.save_new_as_draft, name='save_new_as_draft'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('comment/<int:pk>/remove/', views.remove_comment, name='remove_comment'),
    path('post/<int:pk>/publish/', views.publish_post, name='publish_post'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page': 'blog:home'}),
]

mysite/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse


# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL,
                               null=True)  # since an authorized user is an author
    title = models.CharField(max_length=256)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(default=timezone.now, blank=True, null=True)

    def save_as_draft(self):
        """
        Sets published_date to None and saves post as draft
        """
        self.published_date = None
        self.save()

    def publish(self):
        """
        Sets the published_date and saves the post in the database.
        """
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        """
        Built-in django method indicates where to redirect a user after he creates a post.
        """
        return reverse('blog:home')

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=256)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        """
        Built-in django method indicates where to redirect a user after he creates a post.
        """
        return reverse('blog:post_list')

    def __str__(self):
        return self.text

mysite/blog/forms.py
from django.core import validators

from .models import Comment, Post
from django import forms


class PostForm(forms.ModelForm):
    botcatcher = forms.CharField(widget=forms.HiddenInput, required=False,
                                 validators=[validators.MaxLengthValidator(0)])

    class Meta:
        model = Post
        fields = ('author', 'title', 'text')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'titleinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea textinputclass',
                                          'placeholder': 'Write your text here'})}


class CommentForm(forms.ModelForm):
    botcatcher = forms.CharField(widget=forms.HiddenInput, required=False,
                                 validators=[validators.MaxLengthValidator(0)])
    author = forms.CharField(validators=[validators.MaxLengthValidator(15)])


    author.widget.attrs.update({'class': 'textinputclass',
                                'placeholder': 'Your name (max 15 characters)'})

    class Meta:
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea textinputclass',
                                          'placeholder': 'Your comment'})
            }

mysite/blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from .forms import PostForm, CommentForm
from .models import Post, Comment


from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView


class HomeView(ListView):
    """
    Renders a list of posts ordered by date on a home page
    """
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date') # ('-published_date' = DESC)
        # SELECT * FROM Post
        # WHERE published_date <= now
        # ORDER BY published_date DESC


class AboutView(TemplateView):
    """
    Renders /about page content
    """
    template_name = 'about.html'


class PostDetailView(DetailView):
    """
    Renders post details
    """
    model = Post


class CreatePostView(LoginRequiredMixin, CreateView):
    """
    Renders a form to create a new post
    """
    login_url = '/login'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class UpdatePostView(LoginRequiredMixin, UpdateView):
    """
    Renders a form to update an existing post
    """
    login_url = '/login'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class DeletePostView(LoginRequiredMixin, DeleteView):
    """
    Renders a confirm_delete form
    """
    model = Post
    success_url = reverse_lazy('blog:home')


class DraftListView(LoginRequiredMixin, ListView):
    """
    Renders a list of unpublished posts
    """
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    model = Post
    template_name = 'blog/post_draft_list.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')


@login_required
def save_new_as_draft(request):
    form = PostForm(request.POST)
    if form.is_valid():
        post = form.save(commit=False)
        post.save_as_draft()
        return redirect('blog:post_draft_list')

@login_required
def publish_post(request, pk):
    """
    Realizes .publish() method of class Post
    """
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:home')


def add_comment(request, pk):
    """
    Renders a comment form and saves a new comment to a database
    """
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def remove_comment(request, pk):
    """
    Realizes built-in method .delete()  of class Comment
    """
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

mysite/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block head_block %}
  <title>About</title>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-5 pic-wrap">
    <img class="myphoto"  src="{% static 'images/anya.jpg' %}" alt="">
  </div>

  <div class="col-lg-7">
    <div class="aboutme-wrap">
      <div class="aboutme-text">
        <h1 class="roboto">About me</h1>
        <p>My name is Anna Spitsyna, 29 y.o. I am a beginner Python programmer.</p>
        <p>I've been learning programming since February, 2020.</p>
        <p>I am also interested in front-end technologies.</p>
        <p>I like simple design, my dog and the south of Spain.</p>
        <p>Bloggme is a test single-user blog made on Django as part of a Udemy course.
        This is my first fully consciously made django project.</P>
      </div>
    </div>
  </div>
</div>

{% endblock %}

mysite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Medium Style Editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">


    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lora:wght@500&display=swap" rel="stylesheet">


    <!-- Icon Library Font Awesome -->
    <script src="https://kit.fontawesome.com/3e9e50c803.js" crossorigin="anonymous"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    {% block head_block %}
    {% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark roboto">
    <div class="container">
      <a class="navbar-brand bigbrand" href="{% url 'blog:home' %}">Bloggme</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarNav" aria-controls="navbarNav"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:about' %}">About</a></li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/Granada2013/blog_clone-project">Github</a></li>
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="btn btn-new-post" href="{% url 'blog:post_new' %}">
              <span class="fas fa-pencil-alt"></span> Create new post</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'blog:post_draft_list' %}">My Drafts</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}"> <i class="far fa-user"></i> </a>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container content">
    {% block content %}
    {% endblock %}
  </div>


  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

mysite/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block head_block %}
  <title>New comment</title>
{% endblock %}

{% block content %}
<div class="col-lg-8">
  <h2 class="roboto">New comment</h2>
  {% if form.errors %}
    <ul>
      <li> <small>The name is too long. Must be up to 15 characters.</small></li>
    </ul>
  {% endif %}
  <form class="post-form" method="post">
    {% csrf_token %}

    <p class="form-field">{{ form.author }}</p>
    <p class="form-field">{{ form.text }}</p>

    <input type="submit" class="btn btn-primary" value="Send comment">
  </form>
</div>
  <!-- <script>var editor = new MediumEditor('.editable');</script> -->
{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block head_block %}
  <title>Remove post</title>
{% endblock %}

{% block content %}
  <div class="col-lg-8">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete this post?</p>
    <input type="submit" class="btn btn-outline-danger" value="Delete">
    <a class="btn btn-dark" href="{% url 'blog:post_detail' pk=post.pk %}">Cancel</a>
  </form
  </div>

{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block head_block %}
  <title>Post detail</title>
{% endblock %}


{% block content %}
<div class="col-lg-8">
  <h2 class="posttitle-detail lora">{{ post.title }}</h2>
  {% if post.published_date %}
    <p class="minor">{{ post.published_date }}</p>
    <p class="minor">by {{ post.author }}</p>
  {% else %}
    <p class="minor mb-2">Created: {{ post.created_date }}</p>
      <a class="btn btn-info active mr-2" href="{% url 'blog:publish_post' pk=post.pk %}">
        <span class="far fa-paper-plane icon"></span>Publish</a>
  {% endif %}

  <p class="postcontent-detail text-justify">{{ post.text|safe|linebreaksbr }}</p>

  {% if user.is_authenticated %}
        <a class="btn btn-secondary mr-2" href="{% url 'blog:post_edit' pk=post.pk %}">
          <span class='fas fa-pen icon'></span>Edit</a>
        <a class="btn btn-light" href="{% url 'blog:post_remove' pk=post.pk %}">
          <span class='fas fa-trash-alt icon'></span>Delete</a>
  {% endif %}

  {% if post.published_date %}
    <hr>
    <div class="d-flex flex-row justify-content-between comment-header">
      <h3 class="roboto">Comments</h3>
      <a class="btn btn-primary right" href="{% url 'blog:add_comment' pk=post.pk %}">Add comment</a>
    </div>
    {% for comment in post.comments.all %}
      {% if not comment.was_deleted %}
      <div class="comment-block">
        <div class="d-flex comment-author minor" >
          <span class="fas fa-user-alt icon"></span>
          {{ comment.author }} <span>・</span>{{ comment.created_date }}
        </div>
        <p class="text-justify" style="font-size: 0.8em">{{ comment.text|safe|linebreaksbr }}</p>
        {% if user.is_authenticated %}
          <a class="delete-link" href="{% url 'blog:remove_comment' pk=comment.pk %}">Delete</a>
        {% endif %}
      {% endif %}
      </div>
    {% empty %}
      <p>No comments</p>
    {% endfor %}
  {% endif %}
</div>


{% endblock %}

mysite/blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block head_block %}
  <title>Drafts</title>
{% endblock %}

{% block content %}
<div class="col-lg-8">
  <h1 class="roboto">My Drafts</h1>
  <hr>
    {% for post in post_list %}
      <div class="post">
        <h3> <a class="posttitle lora" href="{% url 'blog:post_detail' pk=post.pk %}">
          {{ post.title }}</a></h3>
        <p class="postcontent">{{ post.text|linebreaksbr|truncatewords:20 }}</p>

        <div class="postdata d-flex flex-row justify-content-between">
          <p class="postdata"> Created: {{ post.created_date|date:"D M Y" }}</p>
          <p class="postdata"> NOT PUBLISHED</p>
        </div>
      {% empty %}
      <p>All your posts are published!</p>
    {% endfor %}
</div>
{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block head_block %}

  {% if not post.instance.pk %}
    <title>New post</title>
  {% else %}
    <title>Edit post</title>
  {% endif %}
{% endblock %}

{% block content %}
<div class="col-lg-8">
  {% if not form.instance.pk %}
    <h1 class="roboto">New Post</h1>
  {% else %}
    <h1 class="roboto">Edit post</h1>
  {% endif %}

  <form class="post-form" method="post">
    {% csrf_token %}
    <table>
      <tr>
        <td class="form-label">{{ form.author.label_tag }}</td>
        <td class="form-field">{{ form.author }}</td>
      </tr>
      <tr>
        <td class="form-label">{{ form.title.label_tag }}</td>
        <td class="form-field">{{ form.title }}</td>
      </tr>
      <tr>
        <td class="form-field" colspan="2">{{ form.text }}</td>
      </tr>
    </table>

    {% if not form.instance.pk %}
      <button type="submit" class="btn btn-info active"
        formaction="{% url 'blog:post_new' %}">
        <span class="far fa-paper-plane icon"></span>Publish</button>

      <button type="submit" class="btn btn-outline-secondary"
        formaction="{% url 'blog:save_new_as_draft' %}">
        Save as draft</button>

    {% else %}
      <button type="submit" class="btn btn-primary"
        formaction="{% url 'blog:post_edit' pk=form.instance.pk %}">
        Save</button>
    {% endif %}
    
  </form>
</div>
  <!-- <script>var editor = new MediumEditor('.editable');</script> -->
{% endblock %}

mysite/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block head_block %}
  <title>Home</title>
{% endblock %}

{% block content %}
<div class="col-lg-8">
  <h1 class="roboto">Welcome to Bloggme!</h1>
  <h6>Check out the latest posts</h6>
  <hr>
  {% for post in post_list %}
  <div class="post">
    <h3> <a  class="posttitle lora" href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h3>
    <p class="postcontent">{{ post.text|linebreaksbr|truncatewords:25 }}</p>
    <div class="postdata d-flex flex-row justify-content-between">
      <p> <span class="fas fa-calendar-alt"></span> {{ post.published_date|date:'b j, Y'}}</p>
      <p> <span class="fas fa-comment"></span> {{ post.comments.count }}</p>
    </div>
  </div>
  {% empty %}
    {% if user.is_authenticated %}
      <p>You have no posts yet. Create your first post now!</p>
    {% else %}
      <p>There're no posts on Bloggme. Login to create one!</p>
    {% endif %}
  {% endfor %}
</div>
{% endblock %}